name: 'Dummy Check Action'
description: 'A dummy action to echo inputs'
inputs:
  input1:
    description: 'First input'
    required: true
  input2:
    description: 'Second input'
    required: true
outputs:
  output1:
    description: 'First output'
  output2:
    description: 'Second output'

runs:
  using: 'composite'
  steps:
    - run: echo "Input 1: ${{ inputs.input1 }}"
      shell: bash
    - run: echo "Input 2: ${{ inputs.input2 }}"
      shell: bash
    - run: echo "::set-output name=output1::${{ inputs.input1 }}"
      shell: bash
    - run: echo "::set-output name=output2::${{ inputs.input2 }}"
      shell: bash
